server:
  port: 8081

spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
    static-path-pattern: /**
  datasource:
    url: jdbc:mysql://localhost/boot_crm?serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

#Mybatis扫描
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  #起别名。可省略写mybatis的xml中的resultType的全路径
  type-aliases-package: com.example.ssmspringboot.usermanage.po


